  version: "3"
  services:
    suzuchi-ginkou-server:
      build:
        context: .
        args:
          NODE_ENV: development
      volumes:
        - ./:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development
        - MONGO_USER=agata
        - MONGO_PASSWORD=mypassword
        - SESSION_SECRET=secret
      command: npm run dev
    suzuchi-ginkou-database:
      environment:
        - MONGO_INITDB_ROOT_USERNAME=agata
        - MONGO_INITDB_ROOT_PASSWORD=mypassword